<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="openapi3" nsURI="http://som.uoc.edu/openapi/3.0.2" nsPrefix="openapi3">
  <eClassifiers xsi:type="ecore:EClass" name="JSONSchemaSubset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//JSONDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMaximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMinimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleOf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainedCollections">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
        eType="#//Schema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" upperBound="-1"
        eType="#//ResponseDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="API" eSuperTypes="#//ParameterContainer #//SchemaContainer #//ParameterContext #//ExternalDocsContext #//ResponseContainer">
    <eOperations name="getAllOperations" upperBound="-1" eType="#//Operation"/>
    <eOperations name="getSchemaByReference" eType="#//Schema">
      <eParameters name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOperationById" eType="#//Operation">
      <eParameters name="operationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getPathByRelativePath" eType="#//Path">
      <eParameters name="relativePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getParameterByReference" eType="#//Parameter">
      <eParameters name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getResponseDefinitionByReference" eType="#//ResponseDefinition">
      <eParameters name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openapi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="info" eType="#//Info" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemes" upperBound="-1"
        eType="#//SchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//Path" unsettable="true" containment="true" eOpposite="#//Path/api"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" eType="#//Components"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" upperBound="-1"
        eType="#//SecurityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Info">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="termsOfService" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//Contact"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" eType="#//License"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="License">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//ParameterContainer #//ParameterContext">
    <eOperations name="getOperationByHTTPMethod" eType="#//Operation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="switch(method) {&#xD;&#xA;&#x9;case &quot;GET&quot;: return getGet();&#xD;&#xA;&#x9;case &quot;POST&quot;: return getPost();&#xD;&#xA;&#x9;case &quot;PUT&quot;: return getPost();&#xD;&#xA;&#x9;case &quot;DELETE&quot;: return getDelete();&#xD;&#xA;&#x9;case &quot;PATCH&quot;: return getPatch();&#xD;&#xA;&#x9;case &quot;OPTIONS&quot;: return getOptions();&#xD;&#xA;&#x9;case &quot;HEAD&quot;: return getHead();&#xD;&#xA;&#x9;default: return null;&#xD;&#xA;}"/>
      </eAnnotations>
      <eParameters name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="get" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="put" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="post" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delete" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patch" eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="api" eType="#//API" eOpposite="#//API/paths"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//ParameterContainer #//ParameterContext #//ExternalDocsContext">
    <eOperations name="getFullPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getHTTPMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagReferences" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" lowerBound="1"
        upperBound="-1" eType="#//Response" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemes" upperBound="-1"
        eType="#//SchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" upperBound="-1"
        eType="#//SecurityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestBody" eType="#//RequestBody"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callbacks" upperBound="-1"
        eType="#//CallbackEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDocs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//SchemaContainer #//JSONSchemaSubset #//ArrayContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//ParameterLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowEmplyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaringContext" eType="#//ParameterContainer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowReserved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//ExampleEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//MediaTypeEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemsDefinition" eSuperTypes="#//JSONSchemaSubset #//ArrayContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="Schema" eSuperTypes="#//JSONSchemaSubset #//SchemaContainer #//ExternalDocsContext">
    <eOperations name="getPropertyByName" eType="#//Property">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxProperties" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minProperties" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allOf" upperBound="-1"
        eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xml" eType="#//XMLElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additonalProperties" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaringContext" eType="#//SchemaContainer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additonalPropertiesAllowed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseDefinition" eSuperTypes="#//SchemaContainer #//SchemaContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//Header" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//Example" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaringContext" eType="#//ResponseContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="#//JSONSchemaSubset #//ArrayContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//ExternalDocsContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityScheme">
    <eOperations name="getSecurityScopeByName" eType="#//SecurityScope">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="for(SecurityScope securityScope: getScopes())&#xD;&#xA;&#x9;if(securityScope.getName().equals(name))&#xD;&#xA;&#x9;&#x9;return securityScope;&#xD;&#xA;return null;"/>
      </eAnnotations>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SecuritySchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//APIKeyLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" eType="#//OAuth2FlowType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizationUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" upperBound="-1"
        eType="#//SecurityScope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Example">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrapped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityScope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterContainer" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaContainer" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseContainer" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDocsContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalDocs" eType="#//ExternalDocs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayContext" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionFormat" eType="#//CollectionFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//ItemsDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemeType">
    <eLiterals name="http"/>
    <eLiterals name="https" value="1"/>
    <eLiterals name="ws" value="2"/>
    <eLiterals name="wss" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterLocation">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="query" value="1"/>
    <eLiterals name="header" value="2"/>
    <eLiterals name="path" value="3"/>
    <eLiterals name="cookie" value="4" literal="cookie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionFormat">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="csv" value="1"/>
    <eLiterals name="ssv" value="2"/>
    <eLiterals name="tsv" value="3"/>
    <eLiterals name="pipes" value="4"/>
    <eLiterals name="multi" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OAuth2FlowType">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="implicit" value="1"/>
    <eLiterals name="password" value="2"/>
    <eLiterals name="application" value="3"/>
    <eLiterals name="accessCode" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="APIKeyLocation">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="query" value="1"/>
    <eLiterals name="header" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SecuritySchemeType">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="basic" value="1"/>
    <eLiterals name="apiKey" value="2"/>
    <eLiterals name="oauth2" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JSONDataType">
    <eLiterals name="unspecified" literal="unspecified"/>
    <eLiterals name="boolean" value="1"/>
    <eLiterals name="integer" value="2"/>
    <eLiterals name="number" value="3"/>
    <eLiterals name="string" value="4"/>
    <eLiterals name="object" value="5"/>
    <eLiterals name="array" value="6" literal="array"/>
    <eLiterals name="file" value="8"/>
    <eLiterals name="null" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityScopes" upperBound="-1"
        eType="#//SecurityScope"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityScheme" eType="#//SecurityScheme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//SchemaContext #//SchemaContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response" eSuperTypes="#//ResponseContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseDefinition" eType="#//ResponseDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//ServerVariableEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerVariableEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ServerVariable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Components">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
        eType="#//SchemaEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" upperBound="-1"
        eType="#//ResponseDefinitionEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//ExampleEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestBodies" upperBound="-1"
        eType="#//RequestBodyEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securitySchemes" upperBound="-1"
        eType="#//SecuritySchemeEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//LinkEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callBacks" upperBound="-1"
        eType="#//CallbackEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaEntry" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//SchemaContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Schema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseDefinitionEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ResponseDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Example"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestBodyEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//RequestBody"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Header"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecuritySchemeEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SecurityScheme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallbackEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Callback"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//MediaTypeEntry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Callback">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callbacks" upperBound="-1"
        eType="#//ExpressionToPath"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//ExampleEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encoding" upperBound="-1"
        eType="#//EncodingEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaTypeEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//MediaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Encoding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//HeaderEntry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowReserved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncodingEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Encoding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionToPath" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Path"/>
  </eClassifiers>
</ecore:EPackage>
